flyway.url=jdbc:postgresql://db:5432/updraft
flyway.user=updraft
flyway.password=updraft
flyway.schemas=updraft
flyway.defaultSchema=updraft
flyway.locations=filesystem:sql
flyway.table=flyway_schema_history
flyway.connectRetries=5
flyway.cleanDisabled=true
